"###################################################################"

"# Created by write_sdc on Mon Jan  6 11:51:19 2014"

"###################################################################"
"set sdc_version 1.7"

"set_wire_load_model -name tsmc090_wl40 -library fast"
"set_load -pin_load 0.002124 [get_ports imem_en_x]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[14]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[13]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[12]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[11]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[10]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[9]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[8]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[7]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[6]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[5]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[4]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[3]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[2]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[1]}]"
"set_load -pin_load 0.002124 [get_ports {imem_addr[0]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[31]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[30]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[29]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[28]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[27]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[26]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[25]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[24]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[23]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[22]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[21]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[20]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[19]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[18]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[17]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[16]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[15]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[14]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[13]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[12]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[11]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[10]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[9]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[8]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[7]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[6]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[5]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[4]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[3]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[2]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[1]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_data_out[0]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[12]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[11]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[10]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[9]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[8]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[7]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[6]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[5]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[4]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[3]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[2]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[1]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_addr[0]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_mem_en_x[0]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_en_x[0]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[31]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[30]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[29]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[28]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[27]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[26]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[25]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[24]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[23]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[22]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[21]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[20]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[19]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[18]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[17]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[16]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[15]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[14]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[13]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[12]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[11]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[10]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[9]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[8]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[7]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[6]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[5]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[4]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[3]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[2]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[1]}]"
"set_load -pin_load 0.002124 [get_ports {fu_LSU_wr_mask_x[0]}]"
"create_clock [get_ports clk]  -name MYCLK  -period 10  -waveform {0 5}"
"set_clock_uncertainty 0.07  [get_clocks MYCLK]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports rstx]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports busy]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[41]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[40]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[39]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[38]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[37]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[36]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[35]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[34]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[33]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[32]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[31]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[30]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[29]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[28]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[27]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[26]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[25]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[24]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[23]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[22]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[21]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[20]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[19]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[18]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[17]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[16]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[15]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[14]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[13]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[12]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[11]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[10]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[9]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[8]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[7]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[6]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[5]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[4]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[3]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[2]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[1]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {imem_data[0]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[14]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[13]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[12]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[11]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[10]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[9]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[8]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[7]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[6]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[5]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[4]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[3]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[2]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[1]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {pc_init[0]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[31]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[30]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[29]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[28]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[27]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[26]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[25]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[24]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[23]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[22]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[21]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[20]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[19]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[18]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[17]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[16]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[15]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[14]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[13]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[12]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[11]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[10]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[9]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[8]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[7]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[6]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[5]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[4]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[3]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[2]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[1]}]"
"set_input_delay -clock MYCLK  -max 0.5  [get_ports {fu_LSU_data_in[0]}]"
"source toplevel.setload"
"source toplevel.setres"
